### PR TITLE
added Sparkfun Pro Micro to id filter

### PR DESCRIPTION
**Pull request by gocivici**
Hi! I'm working on an [Arduino-compatible open-source space mouse](https://github.com/gocivici/trinteract). I added the id codes for the Arduino to the id filter to make this tool compatible with DIY devices. I also commented the `gamepad.axes.length !== 6 ` to make room for devices that have more or less then 6 axes.

### CODE REVIEW

**Comment by chuanqisun** [comment]
Hi @gocivici, since I don't have the hardware, were you able to build the plugin and test it in Figma?

**Comment by gocivici** [comment]
Hi @chuanqisun, yes I tested the plugin in the Figma desktop app. [Here's a video](https://youtu.be/fPkMXDzb_GY) showcasing the plugin running in dev mode with arduino pro micro.

**Comment by chuanqisun** [comment]
That's awesome. I'll publish a release with your change shortly. Thank you for the test video!

**Comment by chuanqisun** [comment]
@gocivici, I have just published the plugin to Figma with [minor refactoring of your code](https://github.com/chuanqisun/spacemouse-anywhere/blob/e79dd9555bc1ab48a641365e3ebf7433dee9f664/apps/figma/ui.html#LL353C1-L357C4). My goal is to keep the SpaceMouse and SparkFun logic separate so it's easier to maintain in the future. Could you do a quick check to see if the published version works for you?

**Comment by gocivici** [comment]
Thanks @chuanqisun! That makes sense, I tested it just now and it doesn't work with the Sparkfun board. In my initial edit, I added both `gamepadName.indexOf("vendor: SparkFun Pro Micro")` and `gamepadName.indexOf("vendor: 1b4f") ` to the list but it looks like only the vendor ID is recognized. Replacing "vendor: SparkFun Pro Micro" with "vendor: 1b4f" would solve this issue.

**Comment by chuanqisun** [comment]
😅that was entirely my mistake. I did that merge without actually testing. I switched to your original vendor hex id and republished the plugin. Thank you for testing and please let me know if it working now.

**Comment by gocivici** [comment]
It's working perfectly now thanks!

**Pull request merged**
